#!/bin/bash
#
# Create symlinks to home folder for dot-files
#
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -s $DIR/bashrc_dotfiles ~/.bashrc_dotfiles
ln -s $DIR/gitconfig ~/.gitconfig
ln -s $DIR/ssh-config ~/.ssh/config

if grep -Fxq "# Added by dot-files" ~/.profile
then
cat <<EOT >> ~/.profile
# Added by dot-files
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc_dotfiles" ]; then
        . "$HOME/.bashrc_dotfiles"
    fi
fi
EOT
fi
