#!/bin/bash
#
# Create symlinks to home folder for dot-files
#
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mv ~/.bashrc ~/.bashrc-ORG
ln -s $DIR/bashrc ~/.bashrc
ln -s $DIR/gitignore ~/.gitignore
ln -s $DIR/gitconfig ~/.gitconfig
ln -s $DIR/ssh-config ~/.ssh/config
