#!/bin/bash

#
# Just include this in "user data" when launching a EC2 instance
# curl -sSL https://raw.githubusercontent.com/bonk-se/dot-files/master/install-aws | bash
#

# Setup the ubuntu user with my custom dot-files
cd /home/ubuntu
sudo apt-get install -y git
mkdir /home/ubuntu/src
cd /home/ubuntu/src
git clone https://github.com/bonk-se/dot-files.git
cd /home/ubuntu/src/dot-files
./install

# Create /www directory with correct owner
sudo mkdir /www
sudo chown -R www-data:www-data /www
cd /www

# Clone GT and setup server
# XXX - Not working due to private repo
#git clone https://github.com/bonk-se/globaltalent.git
#cd /www/globaltalent/setup
#sudo ./install-server
