#!/bin/sh
#
# Embed .srt into a mp4-file
# Optimized for Plex
#
# Usage: add-srt-to-mp4 infile outfile srtfile
#
if [ $# -ne 2 ]; then
    echo $0: usage: $0 inputfile srtfile
    exit 1
fi

MP4Box -out $1 -tmp /var/tmp/ -add $2:hdlr="sbtl:tx3g":lang=eng:group=2:layout=0x60x0x-1:layer=-1:name="English" $1
