#!/bin/sh
#
# Transcode to mp4 + ac3 (copy text)
# Optimized for Plex
#
# Usage: convert-mkv infile outfile
#
if [ $# -ne 2 ]; then
    echo $0: usage: $0 infile outfile
    exit 1
fi

ffmpeg -i $1 -map 0 -acodec ac3 -ac 6 -ab 640k -strict experimental -scodec mov_text -vcodec libx264 -preset slow -crf 14 -level 41 -maxrate 25M -bufsize 10M -f mp4 -map_metadata -1 -pix_fmt yuv420p $2
