#!/bin/sh
#
# Transcode to AC3 and copy video + subs
# Optimized for Plex
#
# Usage: convert-mkv-vcopy infile outfile
#
if [ $# -ne 2 ]; then
    echo $0: usage: $0 infile outfile
    exit 1
fi

ffmpeg -i $1 -map 0 -acodec ac3 -ac 6 -ab 640k -strict experimental -scodec mov_text -c:v copy $2
